window.ENRICHED_ATLAS_SELECTION = [
  {id:'app_clinical3_5',domain:'Artifacts & Image Optimization',title:'Acoustic shadowing and contrast dose'},
  {id:'app_clinical3_49',domain:'Artifacts & Image Optimization'},
  {id:'app_clinical3_50',domain:'Artifacts & Image Optimization',title:'Side-lobe, reverberation, attenuation, and comet-tail artifacts'},
  {id:'app_clinical3_52',domain:'Artifacts & Image Optimization'},
  {id:'app_clinical3_54',domain:'Artifacts & Image Optimization'},
  {id:'app_tips2_444',domain:'Artifacts & Image Optimization'},
  {id:'app_tips2_453',domain:'Artifacts & Image Optimization'},
  {id:'tips2_c4_q7',domain:'Artifacts & Image Optimization'},
  {id:'tips2_c8_q7',domain:'Artifacts & Image Optimization'},

  {id:'app_clinical3_3',domain:'Physics & Doppler Principles',title:'M-mode: reflections along one scan line over time'},
  {id:'app_clinical3_4',domain:'Physics & Doppler Principles',title:'Spectral Doppler: velocity distribution over time'},
  {id:'app_clinical3_13',domain:'Physics & Doppler Principles'},
  {id:'app_clinical3_17',domain:'Physics & Doppler Principles'},
  {id:'app_clinical3_29',domain:'Physics & Doppler Principles'},
  {id:'app_clinical3_56',domain:'Physics & Doppler Principles'},

  {id:'app_clinical3_61',domain:'Technique, Views & M-mode'},
  {id:'app_clinical3_64',domain:'Technique, Views & M-mode'},
  {id:'app_clinical3_66',domain:'Technique, Views & M-mode'},
  {id:'app_clinical3_67',domain:'Technique, Views & M-mode'},
  {id:'app_clinical3_69',domain:'Technique, Views & M-mode'},
  {id:'app_tips2_468',domain:'Technique, Views & M-mode'},
  {id:'app_tips2_676',domain:'Technique, Views & M-mode'},

  {id:'app_clinical3_132',domain:'TEE'},
  {id:'app_clinical3_133',domain:'TEE'},
  {id:'app_clinical3_134',domain:'TEE'},
  {id:'app_clinical3_135',domain:'TEE'},
  {id:'app_clinical3_143',domain:'TEE'},
  {id:'app_clinical3_146',domain:'TEE'},
  {id:'app_clinical3_714',domain:'TEE'},
  {id:'app_clinical3_718',domain:'TEE'},
  {id:'app_clinical3_720',domain:'TEE'},

  {id:'app_clinical3_112',domain:'Contrast & 3D'},
  {id:'app_clinical3_114',domain:'Contrast & 3D'},
  {id:'app_clinical3_120',domain:'Contrast & 3D'},
  {id:'app_clinical3_121',domain:'Contrast & 3D'},
  {id:'app_clinical3_216',domain:'Contrast & 3D'},
  {id:'app_tips2_692',domain:'Contrast & 3D'},

  {id:'app_clinical3_89',domain:'LV Systolic Function'},
  {id:'app_clinical3_90',domain:'LV Systolic Function',title:'Correct non-foreshortened apical LV view'},
  {id:'app_clinical3_91',domain:'LV Systolic Function',title:'Left atrial-focused apical acquisition'},
  {id:'app_clinical3_93',domain:'LV Systolic Function',title:'Correct LVOT diameter measurement'},
  {id:'app_clinical3_100',domain:'LV Systolic Function',title:'ASE 17-segment model in the apical views'},

  {id:'app_clinical3_102',domain:'Strain & Tissue Doppler',title:'Disease-specific global longitudinal strain patterns'},
  {id:'app_clinical3_103',domain:'Strain & Tissue Doppler',title:'Septal strain reduction in HCM with fibrosis'},
  {id:'app_clinical3_238',domain:'Strain & Tissue Doppler'},
  {id:'app_clinical3_256',domain:'Strain & Tissue Doppler'},
  {id:'app_tips2_584',domain:'Strain & Tissue Doppler'},
  {id:'tips2_c53_q7',domain:'Strain & Tissue Doppler'},

  {id:'app_clinical3_94',domain:'Right Heart & PH',title:'IVC size and collapse for right atrial pressure'},
  {id:'app_clinical3_95',domain:'Right Heart & PH',title:'Right atrial pressure estimate from IVC behavior'},
  {id:'app_clinical3_96',domain:'Right Heart & PH',title:'Pulmonary artery pressure from TR velocity'},
  {id:'app_clinical3_97',domain:'Right Heart & PH',title:'RV dimensions in arrhythmogenic cardiomyopathy'},
  {id:'app_clinical3_98',domain:'Right Heart & PH'},
  {id:'app_clinical3_99',domain:'Right Heart & PH',title:'RVSP calculation from the TR signal'},
  {id:'app_clinical3_750',domain:'Right Heart & PH'},
  {id:'app_clinical3_753',domain:'Right Heart & PH'},
  {id:'app_clinical3_754',domain:'Right Heart & PH'},
  {id:'app_clinical3_755',domain:'Right Heart & PH'},
  {id:'app_clinical3_757',domain:'Right Heart & PH'},

  {id:'app_clinical3_198',domain:'Diastolic Function & LA'},
  {id:'app_clinical3_250',domain:'Diastolic Function & LA'},
  {id:'app_clinical3_259',domain:'Diastolic Function & LA'},
  {id:'app_clinical3_263',domain:'Diastolic Function & LA'},
  {id:'app_clinical3_264',domain:'Diastolic Function & LA'},
  {id:'app_clinical3_266',domain:'Diastolic Function & LA'},

  {id:'app_clinical3_101',domain:'Coronary Disease & Ischemia',title:'Coronary territories of the LV segments'},
  {id:'app_clinical3_239',domain:'Coronary Disease & Ischemia'},
  {id:'app_clinical3_240',domain:'Coronary Disease & Ischemia'},
  {id:'app_clinical3_241',domain:'Coronary Disease & Ischemia'},

  {id:'app_clinical3_242',domain:'Cardiomyopathies'},
  {id:'app_clinical3_244',domain:'Cardiomyopathies'},
  {id:'app_clinical3_571',domain:'Cardiomyopathies'},
  {id:'app_clinical3_572',domain:'Cardiomyopathies'},
  {id:'app_clinical3_574',domain:'Cardiomyopathies'},
  {id:'app_clinical3_577',domain:'Cardiomyopathies'},
  {id:'app_clinical3_578',domain:'Cardiomyopathies'},
  {id:'app_clinical3_582',domain:'Cardiomyopathies'},

  {id:'app_clinical3_675',domain:'Pericardial Disease'},
  {id:'app_clinical3_676',domain:'Pericardial Disease'},
  {id:'app_clinical3_677',domain:'Pericardial Disease'},
  {id:'app_clinical3_685',domain:'Pericardial Disease'},
  {id:'app_clinical3_686',domain:'Pericardial Disease'},
  {id:'app_ramdas3_789',domain:'Pericardial Disease'},
  {id:'app_ramdas3_923',domain:'Pericardial Disease'},
  {id:'app_tips2_663',domain:'Pericardial Disease'},

  {id:'app_clinical3_319',domain:'Aortic Valve Disease'},
  {id:'app_clinical3_320',domain:'Aortic Valve Disease'},
  {id:'app_clinical3_337',domain:'Aortic Valve Disease'},
  {id:'app_clinical3_342',domain:'Aortic Valve Disease'},
  {id:'app_clinical3_352',domain:'Aortic Valve Disease'},
  {id:'app_tips2_494',domain:'Aortic Valve Disease'},
  {id:'app_tips2_496',domain:'Aortic Valve Disease'},

  {id:'app_clinical3_375',domain:'Mitral Valve Disease'},
  {id:'app_clinical3_377',domain:'Mitral Valve Disease'},
  {id:'app_clinical3_379',domain:'Mitral Valve Disease'},
  {id:'app_clinical3_380',domain:'Mitral Valve Disease'},
  {id:'app_clinical3_381',domain:'Mitral Valve Disease'},
  {id:'app_clinical3_388',domain:'Mitral Valve Disease'},
  {id:'app_clinical3_518',domain:'Mitral Valve Disease'},
  {id:'app_clinical3_528',domain:'Mitral Valve Disease'},

  {id:'app_clinical3_420',domain:'Tricuspid & Pulmonic'},
  {id:'app_clinical3_422',domain:'Tricuspid & Pulmonic'},
  {id:'app_clinical3_540',domain:'Tricuspid & Pulmonic'},
  {id:'app_clinical3_543',domain:'Tricuspid & Pulmonic'},
  {id:'app_clinical3_559',domain:'Tricuspid & Pulmonic'},
  {id:'app_ramdas3_881',domain:'Tricuspid & Pulmonic'},

  {id:'app_clinical3_338',domain:'Prosthetic Valves'},
  {id:'app_clinical3_437',domain:'Prosthetic Valves'},
  {id:'app_clinical3_438',domain:'Prosthetic Valves'},
  {id:'app_clinical3_440',domain:'Prosthetic Valves'},
  {id:'app_clinical3_442',domain:'Prosthetic Valves'},
  {id:'app_clinical3_443',domain:'Prosthetic Valves'},
  {id:'app_clinical3_449',domain:'Prosthetic Valves'},
  {id:'app_clinical3_530',domain:'Prosthetic Valves'},
  {id:'app_tips2_456',domain:'Prosthetic Valves'},

  {id:'app_clinical3_463',domain:'Endocarditis'},
  {id:'app_clinical3_468',domain:'Endocarditis'},
  {id:'app_clinical3_470',domain:'Endocarditis'},
  {id:'app_clinical3_476',domain:'Endocarditis'},
  {id:'app_clinical3_477',domain:'Endocarditis'},
  {id:'app_clinical3_479',domain:'Endocarditis'},
  {id:'app_clinical3_482',domain:'Endocarditis'},
  {id:'app_clinical3_483',domain:'Endocarditis'},
  {id:'app_clinical3_487',domain:'Endocarditis'},
  {id:'app_clinical3_489',domain:'Endocarditis'},

  {id:'app_clinical3_771',domain:'Cardiac Masses & Embolic Source'},
  {id:'app_clinical3_773',domain:'Cardiac Masses & Embolic Source'},
  {id:'app_clinical3_774',domain:'Cardiac Masses & Embolic Source'},
  {id:'app_clinical3_775',domain:'Cardiac Masses & Embolic Source'},
  {id:'app_clinical3_777',domain:'Cardiac Masses & Embolic Source'},
  {id:'app_clinical3_779',domain:'Cardiac Masses & Embolic Source'},
  {id:'app_clinical3_782',domain:'Cardiac Masses & Embolic Source'},
  {id:'app_clinical3_784',domain:'Cardiac Masses & Embolic Source'},

  {id:'app_clinical3_148',domain:'Diseases of the Aorta'},
  {id:'app_clinical3_170',domain:'Diseases of the Aorta'},
  {id:'app_clinical3_694',domain:'Diseases of the Aorta',title:'Anomalous left circumflex coronary artery arising from the right coronary cusp'},
  {id:'app_clinical3_697',domain:'Diseases of the Aorta'},
  {id:'app_clinical3_700',domain:'Diseases of the Aorta'},

  {id:'app_clinical3_792',domain:'Adult Congenital'},
  {id:'app_clinical3_794',domain:'Adult Congenital'},
  {id:'app_clinical3_817',domain:'Adult Congenital'},
  {id:'app_clinical3_820',domain:'Adult Congenital'},
  {id:'app_clinical3_823',domain:'Adult Congenital'},
  {id:'app_clinical3_825',domain:'Adult Congenital'},
  {id:'app_clinical3_826',domain:'Adult Congenital'}
];
